version: 0.0
os: linux
files:
  - source: /
    destination: /appdir
hooks:
  ApplicationStop:
    - location: appdir/danielr-app/stop.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: appdir/danielr-app/start.sh
      timeout: 300
      runas: root
