version: 0.0
os: linux
files:
  - source: /
    destination: /appdir/appdata
hooks:
  ApplicationStop:
    - location: appdir/appdata/scripts/stop.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: appdir/appdata/scripts/start.sh
      timeout: 300
      runas: root
